merketoaspnet/Models/ViewModels/AllProductsViewModel.cs
using merketoaspnet.Models.Dtos;

namespace merketoaspnet.Models.ViewModels
{
    public class AllProductsViewModel
    {
        public string? Title { get; set; }
        public IEnumerable<Product> AllProducts { get; set; } = new List<Product>();
    }
}

merketoaspnet/Models/ViewModels/CollectionViewModel.cs
using merketoaspnet.Migrations;
using merketoaspnet.Models.Dtos;

namespace merketoaspnet.Models.ViewModels
{
    public class CollectionViewModel
    {
        public string? Title { get; set; }

        public IEnumerable<Product> NewProducts { get; set; } = new List<Product>();
        public IEnumerable<Product> PopularProducts { get; set; } = new List<Product>();
        public IEnumerable<Product> FeaturedProducts { get; set; } = new List<Product>();
    }
}

merketoaspnet/Models/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace merketoaspnet.Models.ViewModels
{
    public class ContactViewModel
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "This field is required")]
        public string FirstName { get; set; } = null!;


        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        public string LastName { get; set; } = null!;


        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Email address is not formatted correctly")]
        public string Email { get; set; } = null!;

        [Required(ErrorMessage = "This field is required")]
        public string Message { get; set; } = null!;
    }
}

merketoaspnet/Models/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace merketoaspnet.Models.ViewModels
{
    public class LoginViewModel
    {
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; } = null!;

        [DataType(DataType.Password)]
        public string Password { get; set; } = null!;

        public bool RememberMe { get; set; } = false;
    }
}

merketoaspnet/Controllers/AccessDeniedController.cs
using Microsoft.AspNetCore.Mvc;

namespace merketoaspnet.Controllers
{
    public class AccessDeniedController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

merketoaspnet/Controllers/ContactsController.cs
using merketoaspnet.Helpers.Repositories;
using merketoaspnet.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace merketoaspnet.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactRepo _contactRepo;

        public ContactsController(ContactRepo contactRepo)
        {
            _contactRepo = contactRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Index(ContactViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _contactRepo.AddAsync(new Models.Entities.ContactFormEntity
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Email = viewModel.Email,
                    Message = viewModel.Message
                });

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }


    }
}

merketoaspnet/Controllers/LoginController.cs
using merketoaspnet.Helpers.Services;
using merketoaspnet.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace merketoaspnet.Controllers
{
    public class LoginController : Controller
    {
        private readonly AuthenticationService _authenticationService;

        public LoginController(AuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel viewModel)
        {
            if (ModelState.IsValid && viewModel.Email.Contains("administrator")) 
            {
                if (await _authenticationService.LoginUserAsync(viewModel))
                {
                        return RedirectToAction("Index", "Administrator");
                }
                
            }
            else if (ModelState.IsValid)
            {
                if (await _authenticationService.LoginUserAsync(viewModel))
                {
                    return RedirectToAction("Index", "User");
                }


            }
            if (ModelState.IsValid)
            { 
              if  (!await _authenticationService.LoginUserAsync(viewModel))
                
                return RedirectToAction("Index", "AccessDenied");
            }



            return View(viewModel);
        }
    }
}

merketoaspnet/Controllers/LogoutController.cs
using merketoaspnet.Helpers.Services;
using merketoaspnet.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace merketoaspnet.Controllers
{
   
    public class LogoutController : Controller
    {
        private readonly AuthenticationService _authenticationService;

        public LogoutController(AuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public async Task<IActionResult> Index()
        {

                    await _authenticationService.LogoutUserAsync();
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    
           
        }
    }
}

merketoaspnet/Controllers/ProductDetailsController.cs
using merketoaspnet.Helpers.Services;
using Microsoft.AspNetCore.Mvc;

namespace merketoaspnet.Controllers
{
    public class ProductDetailsController : Controller
    {
        private readonly ProductService _productService;

        public ProductDetailsController(ProductService productService)
        {
            _productService = productService;
        }

        public async Task <IActionResult> Index(string articleNumber)
        {
            var product = await _productService.GetProductByArticleNumberAsync(articleNumber);
            return View(product);
        }
    }
}

merketoaspnet/Controllers/RegistrationController.cs
using merketoaspnet.Helpers.Services;
using merketoaspnet.Models.Entities;
using merketoaspnet.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace merketoaspnet.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly UserManager<UserEntity> _userManager;
        private readonly AuthenticationService _authenticationService;
        public RegistrationController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
        {
            _userManager = userManager;
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                if (!await _userManager.Users.AnyAsync(x => x.Email == viewModel.Email))
                {
                    if(await _authenticationService.RegisterUserAsync(viewModel))
                    return RedirectToAction("Index", "Login");
                }
                else
                    ModelState.AddModelError("", "A user with this email already exists");
            }
            return View(viewModel);
        }
    }
}

merketoaspnet/Views/Partials/_AccessDenied.cshtml
<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
        <div class="col-6">
            <div class="access-denied-wrapper">
                <div class="access-denied">
                    Access is denied. Return to   <a class="link" asp-controller="Login" asp-action="Index">Login</a> and try again.
                </div>
            </div>
        </div>

    </div>
</div>

merketoaspnet/Views/Partials/_AllProducts.cshtml
@model AllProductsViewModel

<section class="best-collection">
    <div class="container">
   
        <h1 class="products-title">@Model.Title</h1>
       
        <div class="collection-grid">
            @foreach (var product in Model.AllProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="headphones-image" src="@product.Image" alt="Picture of headphones" />
                    <div class="body">
                        <div class="title">@product.VendorName @product.ProductName</div>
                        
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                
            }
        </div>
    </div>
        </section>

merketoaspnet/Views/Partials/_BackOffice.cshtml
@inject UserAdministratorService userAdministratorService



<partial name="/Views/Partials/_SignedInHeader.cshtml" />
<div class="container-bo min-vh-100">
    <div>
        <h2 class="bo-title">Backoffice roles: </h2>

        

        @foreach (var user in await userAdministratorService.GetUsersAsync())
        {



            <div class="roles-container">
                <div class="assigned-role"> @user.Email </div>
                

                @foreach (var role in user.NameOfRoles)
                {
                    <div class="assigned-title">@role</div>
                }

            </div>
        }
    </div>
</div>

merketoaspnet/Views/Partials/_Collection.cshtml
@model ProductByTagsViewModel

﻿<section class="best-collection my-4">
    <div class="container">
        <h1 class="products-title">@Model.Title</h1>
       
        <div class="collection-grid">
            @foreach (var product in Model.NewProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img src="@product.Image" alt="Picture of headphones" />
                    <div class="body">
                        <div class="title">@product.VendorName @product.ProductName</div>
                        
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                
            }
        </div>
        <div class="collection-grid">
            @foreach (var product in Model.PopularProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img src="@product.Image" alt="A picture of headphones">
                    <div class="body">
                        <div class="title">@product.VendorName @product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>
        <div class="collection-grid">
            @foreach (var product in Model.FeaturedProducts)
            {
                <a asp-action="ProductDetails" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img src="@product.Image" alt="A picture of headphones">
                    <div class="body">
                        <div class="title">@product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>
        
    </div>
</section>

merketoaspnet/Views/Partials/_Contact.cshtml
@model ContactViewModel


<div class="container">
    <div class="contact-container">
        <div class="col-6">
            <form method="post" asp-action="Index" asp-controller="Contacts" novalidate>
                <div class="mb-3">
                    <label asp-for="FirstName" class="form-label my-2"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="LastName" class="form-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Message" class="form-label"></label>
                    <textarea asp-for="Message" class="form-control" rows="6"> </textarea>
                    <span asp-validation-for="Message" class="small text-danger"></span>
                </div>

                <div class="mt-3">
                    <button class="btn btn-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

merketoaspnet/Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year bmerketo. All right reserved.
    </div>
</footer>

merketoaspnet/Views/Partials/_Front.cshtml
<section class="showcase">
    <div class="container">
        <div class="content">
            <div class="ingress">Welcome to Merketo Headphones</div>
            <div class="title">Find headphones and buy elsewhere</div>
             
            <button class="btn-theme">
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="1050" class="front-link" >
                To OkaySound123
                </a>
            </button>
            
        </div>
        <div class="content-image">
            <img src="https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="A picture of headphones">
        </div>
    </div>
</section>

merketoaspnet/Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <div class="logo"><img src="../images/logo.svg" alt="">bmerketo</div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="Home" asp-action="Index">HOME</a>
            <a class="link" asp-controller="Home" asp-action="Products">PRODUCTS</a>
            <a class="link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="Login" asp-action="Index">Login</a>
            <a class="link" asp-controller="Registration" asp-action="Index">Register</a>
            
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-solid fa-bars"></i>
            </button>
        </div>
    </div>
</header>

merketoaspnet/Views/Partials/_Login.cshtml
@model LoginViewModel

<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="col-6">
        <form asp-action="Index" asp-controller="Login" method="post" novalidate>
            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" onkeyup="validateEmail" />
                <small><span asp-validation-for="Email" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" onkeyup="validatePassword" />
                <small><span asp-validation-for="Password" class="text-danger"></span></small>
            </div>

            <div class="rememberme">
                    
                    <input type="checkbox" asp-for="RememberMe" />
                    <label asp-for="RememberMe"> Remember Me</label>
            </div>

            <div class="d-grid mb-5">
                <button type="submit" class="btn btn-success mt-2">Login</button>
            </div>

        </form>
    </div>

</div>
</div>

merketoaspnet/Views/Partials/_ProductDetails.cshtml
@using merketoaspnet.Models.Dtos;

@model Product


<div class="container">
    <div class="product-details-container">
       
        <img class="product-details-img" src="@Model.Image" alt="A picture of headphones"/>
        <div class="product-details-wrapper">
            <div class="product-details-details">@Model.VendorName @Model.ProductName</div>

            <div class="product-details-details">@Model.Ingress</div>

            <div class="product-details-details">@Model.Description</div>
            <div class="product-details-details">Price: @Model.Price SEK</div>
           
        </div>

    </div>
</div>

merketoaspnet/Views/Partials/_ProductsByTags.cshtml
@model ProductByTagsViewModel

﻿<section class="best-collection my-4">
    <div class="container">
        <h1 class="products-title">@Model.Title</h1>
       
        <div class="collection-grid">
            @foreach (var product in Model.NewProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="headphones-image" src="@product.Image" alt="Picture of headphones" />
                    <div class="body">
                        <div class="title">@product.VendorName @product.ProductName</div>
                        
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                
            }
        </div>
        <div class="collection-grid">
            @foreach (var product in Model.PopularProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="headphones-image" src="@product.Image" alt="A picture of headphones">
                    <div class="body">
                        <div class="title">@product.VendorName @product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>
        <div class="collection-grid">
            @foreach (var product in Model.FeaturedProducts)
            {
                <a asp-action="ProductDetails" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="headphones-image" src="@product.Image" alt="A picture of headphones">
                    <div class="body">
                        <div class="title">@product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>
        
    </div>
</section>

merketoaspnet/Views/Partials/_Registration.cshtml
@model RegisterViewModel

<div class="container">
    <div class="register-container">
    <div class="col-6">
        <form asp-action="Index" asp-controller="Registration" method="post" novalidate>
            <div class="mb-3">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="FirstName" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="LastName" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" onkeyup="validateEmail" />
                <small><span asp-validation-for="Email" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" onkeyup="validatePassword" />
                <small><span asp-validation-for="Password" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="StreetName" class="form-label"></label>
                <input asp-for="StreetName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="StreetName" class="text-danger"></span></small>
            </div>
            <div class="mb-3">
                <label asp-for="PostalCode" class="form-label"></label>
                <input asp-for="PostalCode" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="PostalCode" class="text-danger"></span></small>
            </div>
            <div class="mb-3">
                <label asp-for="City" class="form-label"></label>
                <input asp-for="City" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="City" class="text-danger"></span></small>
            </div>

            <div class="d-grid mb-5">
                <button type="submit" class="btn btn-success mt-2">Register</button>
            </div>

        </form>
    </div>
    </div>
</div>

merketoaspnet/Views/Partials/_SignedInHeader.cshtml
<header class="bo-header">
    <div class="container bo-header">
        <div class="logo"><img src="images/logo.svg" alt="">bmerketo</div>
        <nav id="menu" class="menu-links">
            <a class="bo-link" asp-controller="Home" asp-action="Index">HOME</a>
            <a class="bo-link" asp-controller="Home" asp-action="Products">PRODUCTS</a>
            <a class="bo-link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="bo-link logout" asp-controller="Logout" asp-action="Index">Logout</a>
           

        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-solid fa-bars"></i>
            </button>
        </div>
    </div>
</header>

merketoaspnet/Views/Partials/_UserProfilePage.cshtml
<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
        <div class="col-6">
            <div class="access-denied-wrapper">
                <div class="access-denied">
                   This is your profile page.
                </div>
            </div>
        </div>

    </div>
</div>